export type MapId = "schoolyard" | "space-station" | "mountain-pass";
export type MapTheme = MapId;
export type TrackBoundary = "blocked" | "fall";
export type CourseType = "loop" | "linear";
export type MapPoint = Readonly<{ x: number; y: number }>;
export type MapRect = Readonly<{ x: number; y: number; width: number; height: number }>;
export type MapPalette = Readonly<{
  trackA: string;
  trackB: string;
  trackEdge: string;
  trackSpeck: string;
  infieldA: string;
  infieldB: string;
  infieldSpeck: string;
  exteriorA: string;
  exteriorB: string;
  exteriorBase: string;
  exteriorSpeck: string;
  outerLine: string;
  innerLine: string;
  laneLine: string;
  accent: string;
}>;
export type MapDefinition = Readonly<{
  id: MapId;
  name: string;
  tagline: string;
  theme: MapTheme;
  courseType: CourseType;
  trackBoundary: TrackBoundary;
  worldWidth: number;
  worldHeight: number;
  trackPath: readonly MapPoint[];
  trackWidth: number;
  startPoint: MapPoint;
  spawnPoints: readonly MapPoint[];
  respawnPoints: readonly MapPoint[];
  checkpoints: readonly Readonly<MapRect & { spawnX: number; spawnY: number }>[];
  finishGate: MapRect;
  palette: MapPalette;
  pitZones: readonly MapRect[];
  jumpPads: readonly Readonly<MapRect & { pushX: number; pushY: number }>[];
  spinners: readonly Readonly<{ x: number; y: number; radius: number; speed: number }>[];
  rockBarriers: readonly MapRect[];
  rollingRocks: Readonly<{
    firstDelay: number;
    minDelay: number;
    randomDelay: number;
    speed: number;
    radius: number;
    spawnOffsets: readonly number[];
  }> | null;
}>;

export const MAP_IDS: readonly MapId[];
export const DEFAULT_MAP_ID: MapId;
export const MAP_DEFINITIONS: Readonly<Record<MapId, MapDefinition>>;
export function getMapDefinition(value?: unknown): MapDefinition;
export function isMapId(value: unknown): value is MapId;
